services:
    mysql:
        image: mariadb:${MARIADB_VERSION}
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - data:/var/lib/mysql
        networks:
            - backend
        ports:
            - "3306:3306"
        container_name: mysql

    phpmyadmin:
        image: phpmyadmin:${PHPMYADMIN_VERSION}
        restart: always
        environment:
            PMA_HOST: mysql
        depends_on:
            - mysql
        networks:
            - backend
        ports:
            - "8080:80"
        volumes:
            - data:/var/lib/phpmyadmin
        container_name: phpmyadmin

    php:
        build:
            context: "./php/"
            args:
                PHP_VERSION: ${PHP_VERSION}
        restart: unless-stopped
        networks:
            - backend
        volumes:
            - ${PROJECT_ROOT}:/var/www/html/
        container_name: php

    apache:
        build:
            context: "./apache/"
            args:
                APACHE_VERSION: ${APACHE_VERSION}
        restart: unless-stopped
        depends_on:
            - php
            - mysql
        networks:
            - frontend
            - backend
        ports:
            - "80:80"
        volumes:
            - ${PROJECT_ROOT}:/var/www/html/
        container_name: apache

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge

volumes:
    data:
